#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🧵 Running lint-staged..."
pnpm lint-staged

echo "🔍 Running type check..."
pnpm typecheck

echo "🏗️ Building app..."
pnpm build

echo "🚦 Running Lighthouse performance check..."
pnpm lh:check
